
DROP TABLE actors CASCADE CONSTRAINTS;
CREATE TABLE actors(NAME VARCHAR2(13) CONSTRAINT PK_ACT PRIMARY KEY,
JOB VARCHAR(10), GENDER CHAR(5), LOC VARCHAR2(15), FILM VARCHAR2(15));

DROP TABLE DRAMA CASCADE CONSTRAINTS;
CREATE TABLE DRAMA (DNAME VARCHAR2(15) CONSTRAINT PK_DRAMA PRIMARY KEY,
GENRE VARCHAR(10));

INSERT INTO ACTORS VALUES ( '박보검','MODEL','남','한남동','청춘기록');
INSERT INTO ACTORS VALUES ( '박소담','ARTIST','여','한남동','청춘기록');
INSERT INTO ACTORS VALUES ( '한여름','DESIGNER','여','성북동','연애의발견');
INSERT INTO ACTORS VALUES ( '강태하','CEO','남','청담동','연애의발견');
INSERT INTO ACTORS VALUES ( '오동백','CEO','여','옹산','동백꽃');
INSERT INTO ACTORS VALUES ( '황용식','POLICE','남','옹산','동백꽃');
INSERT INTO ACTORS VALUES ( '황시목','PROSECUTOR','남','성수동','비밀의숲');
INSERT INTO ACTORS VALUES ( '한여진','DETECTIVE','여','연남동','비밀의숲');

INSERT INTO DRAMA VALUES ( '청춘기록','R_C');
INSERT INTO DRAMA VALUES ( '연애의발견','R_C');
INSERT INTO DRAMA VALUES ( '동백꽃','R_C');
INSERT INTO DRAMA VALUES ( '비밀의숲','CRIME');

UPDATE actors SET NAME = '조승우' WHERE NAME = '황시목';
UPDATE actors SET JOB = 'DETECTIVE' WHERE NAME = '황용식';
UPDATE actors SET LOC = '분당' WHERE NAME = '한여진';
